spring:
  application:
    name: constituciones-linea-base
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/constituciones
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: ${PORT:8081}
  servlet:
    context-path: /linea-base

logging:
  level:
    root: INFO
    org:
      springframework:
        web:
          filter: DEBUG
client:
  transversal: http://localhost:8085/transversal/v1